DATALOADER:
  ASPECT_RATIO_GROUPING: True
  NUM_WORKERS: 4
  SIZE_DIVISIBILITY: 32
DATASETS:
  TEST: ('cityscapes_fine_instanceonly_seg_val_cocostyle',)
  TRAIN: ('cityscapes_fine_instanceonly_seg_train_cocostyle',)
  TRAIN_PATH: "./datasets/"
INPUT:
  MAX_SIZE_TEST: 1333
  MAX_SIZE_TRAIN: 1333
  MIN_SIZE_RANGE_TRAIN: (-1, -1)
  MIN_SIZE_TEST: 800
  MIN_SIZE_TRAIN: (640, 192)
  PIXEL_MEAN: [102.9801, 115.9465, 122.7717]
  PIXEL_STD: [1.0, 1.0, 1.0]
  TO_BGR255: True
MODEL:
  DEPTH:
    AVG_REPROJECTION: False
    FRAME_IDS: [0, -1, 1]
    LEARNING_RATE: 0.0001
    MAX_DEPTH: 100.0
    MIN_DEPTH: 0.1
    NUM_CH_DEC: [64, 64, 128, 256, 512]
    NUM_CH_ENC: [64, 64, 128, 256, 512]
    NUM_LAYERS: 50
    NUM_OUTPUT_CHANNELS: 1
    NUM_SCALES: 4
    POSE_FRAMES_INPUT: "pair"
    POSE_MODEL_TYPE: "shared"
    SCALES: [0, 1, 2, 3]
    SCHEDULER_STEP_SIZE: 15
    SMOOTH_WEIGHT: 0.001
    USE_SKIPS: True
  DEVICE: "cuda"
  EMBED_MASK:
    BOX_PADDING: 0.0
    BOX_TO_MARGIN_BLOCK: True
    BOX_TO_MARGIN_SCALE: 800
    CENTERNESS_ON_REG: True
    CENTER_ON: True
    CENTER_POS_RADIOS: 1.5
    EMBED_DIM: 32
    FIX_MARGIN: False
    FPN_INTEREST_SPLIT: (64, 128, 256, 512)
    FPN_STRIDES: [8, 16, 32, 64, 128]
    HEAD_NUM_CONVS: 4
    INFERENCE_TH: 0.05
    IOU_LOSS_TYPE: "giou"
    LOSS_ALPHA: 0.25
    LOSS_GAMMA: 2.0
    LOSS_MASK_ALPHA: 0.5
    LOSS_SMOOTH_ALPHA: 0.1
    MASK_NUM_CONVS: 4
    MASK_SCALE_FACTOR: 2
    MASK_TH: 0.5
    NMS_TH: 0.6
    NORM_REG_TARGETS: True
    NUM_CLASSES: 81
    POSTPROCESS_MASKS: False
    PRE_NMS_TOP_N: 1000
    PRIOR_MARGIN: 2.0
    PRIOR_PROB: 0.01
    SAMPLE_IN_MASK: True
    SAMPLE_POS_IOU_TH: 0.5
    USE_DCN_IN_TOWER: False
  MASK_LR: 0.01
  MASK_WEIGHT_DECAY: 0.0005
  NAME: "instanceDepth"
  NUM_EPOCHS: 50
OUTPUT_DIR: "output/embedmask_r50/"
PATHS_CATALOG: "/home/tengfeihan/Downloads/monodepth2-master/config/paths_catalog.py"
SOLVER:
  BASE_LR: 0.001
  BIAS_LR_FACTOR: 2
  CHECKPOINT_PERIOD: 2500
  DCONV_OFFSETS_LR_FACTOR: 1.0
  GAMMA: 0.1
  IMS_PER_BATCH: 8
  MAX_ITER: 200000
  MOMENTUM: 0.9
  STEPS: (30000,)
  WARMUP_FACTOR: 0.3333333333333333
  WARMUP_ITERS: 500
  WARMUP_METHOD: "linear"
  WEIGHT_DECAY: 0.0005
  WEIGHT_DECAY_BIAS: 0
TEST:
  DETECTIONS_PER_IMG: 100
  EXPECTED_RESULTS: []
  EXPECTED_RESULTS_SIGMA_TOL: 4
  IMS_PER_BATCH: 8
